### ISSUE TITLE
Sagemath Cloud API

### ISSUE THREAD

**Issue by PeterBocan** [sagemath/cloud#101]
Hello folks, it would be really nice to have access to projects (and files) stored on the cloud. Upload/Download/Execute files on the cloud. 

That's a bit rough estimate what it should/could do.

**Comment by haraldschilly** [comment]
possible duplicate of #60

**Comment by Eulerianial** [comment]
Harald, so this work is in progress. Am I right?

**Comment by haraldschilly** [comment]
this ticket is closed, so no. there above your comment is a pointer to #60 ... but so far that's all rather vague. What would be your use case or why are you asking?
