### ISSUE TITLE
Can't install.packages("RCurl") in R. Missing libcurl-dev?

### ISSUE THREAD

**Issue by macieksk** [sagemath/cloud#114]
I can't install package RCurl in R and other packages depending on it. 
I suppose the problem is missing package libcurl-dev.

Or possibly  libcurl4-openssl-dev needs to be installed specifically.

``` install.packages("RCurl") ```
```
Installing package into ‘/projects/e45b7bab-3a7e-4939-a0ec-2081b92505b1/R/x86_64-unknown-linux-gnu-library/3.0’
(as ‘lib’ is unspecified)
trying URL 'http://cran.r-project.org/src/contrib/RCurl_1.95-4.1.tar.gz'
Content type 'application/x-gzip' length 870915 bytes (850 Kb)
opened URL
==================================================
downloaded 850 Kb

* installing *source* package ‘RCurl’ ...
** package ‘RCurl’ successfully unpacked and MD5 sums checked
checking for curl-config... no
Cannot find curl-config
ERROR: configuration failed for package ‘RCurl’
* removing ‘/projects/e45b7bab-3a7e-4939-a0ec-2081b92505b1/R/x86_64-unknown-linux-gnu-library/3.0/RCurl’

The downloaded source packages are in
	‘/tmp/RtmpZ0LaMy/downloaded_packages’
Warning message:
In install.packages("RCurl") :
  installation of package ‘RCurl’ had non-zero exit status
```

In shell:
```
~$ locate curl-config
~$ locate libcurl | head
/usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.3
/usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4
/usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4.2.0
/usr/lib/x86_64-linux-gnu/libcurl.so.3
/usr/lib/x86_64-linux-gnu/libcurl.so.4
/usr/lib/x86_64-linux-gnu/libcurl.so.4.2.0
```

Relevant RCurl installation help: http://www.omegahat.org/RCurl/FAQ.html

**Comment by salamon-aska** [comment]
the same question~

solution as follower

sudo apt-get install aptitude

sudo apt-get install libcurl4-openssl-dev

sudo apt-get install libxml2-dev

**Comment by haraldschilly** [comment]
RCurl is installed by default in sage 6.7 on SMC

**Comment by shakraz** [comment]
hi there
maybe my experience will be handful for someone.
so, after facing error message about dependency try to run:
sudo apt-get install libxml2-dev
most likely, you will will face this message again, next step is:
apt-get -f install
and finally repeat step one.

**Comment by JackieMium** [comment]
`sudo apt install libcurl4-openssl-dev` solved the problem. Thanks guys!

**Comment by JulienPascal** [comment]
I applied the solution from @salamon-aska and now it works fine. Thanks.

**Comment by retrodata** [comment]
sudo apt install libcurl4-openssl-dev     Using this gives me an error, I need to install twitteR and it has curl package as dependency. I keep getting this error---- **Error: unexpected symbol in "sudo apt"**

**Comment by haraldschilly** [comment]
@retrodata please send us a support request by clicking on "help" and don't bother with this ticket here. The library is already installed, though.

**Comment by retrodata** [comment]
Thank you. I posted my question. What do you mean by "library already installed"?
I will provide you some context to my problem: 
I am trying to install "twitteR" and "ROAuth" packages for R version 3.3.1. The installations are not successful due to other dependencies involved like installing "curl"package. Installing "curl" also turns out  unsuccessful .I am unable to figure what the problem is and how to solve it. Is there a path that needs to be fixed? If yes, how do I do that?

**Comment by haraldschilly** [comment]
Where did you post it? I mean to contact support, or email to help@sagemath.com ... we also need to know your project ID.

Besides that, `dpkg -L libcurl4-openssl-dev` shows you all the installed files, so it is installed.

**Comment by retrodata** [comment]
Oh! I misunderstood what you said and posted to RStudio support. I have mailed my problem to help@sagemath.com , I don't have any project ID. I am a beginner in R and familiarizing myself with the language. I have posted my query here as I am facing similar problem to the issue being discussed.

**Comment by haraldschilly** [comment]
Well, this issue is only for the https://cloud.sagemath.com platform and that help address for issues with it. We don't give (commercial) support for your own private R endeavours :wink:

**Comment by retrodata** [comment]
Oh! I am sorry , I didn't realize that. Thank you for your time to reply back.

**Comment by saamm** [comment]
I can seem to install swirl in R-3.4.3 in ubuntu trusty I keep getting the error that curl, httr and some other dependencies has non-zero exit status. I dont really know what that means. Also when I try to install libcur14-openssl-dev using terminal, I keep getting the error unable to locate the package.
