### ISSUE TITLE
in latex editor pages can sometimes get repeated

### ISSUE THREAD

**Issue by williamstein** [sagemath/cloud#116]
I've never seen this before now, but when working on a large document today (with somebody else), I frequently saw cases where the same page preview appeared multiple times in the png preview area, but of course not in the original LaTeX document.
The fix will likely be to make the code that removes an old page on update more robust (there's no relevant tracebacks in the javascript console log).  

![screen shot 2014-03-22 at 5 02 19 pm](https://f.cloud.github.com/assets/1276278/2492280/82243ad2-b21e-11e3-83bc-4f18f8585b5c.png)

**Comment by haraldschilly** [comment]
I'm closing this, given the date and that I vaguely remember that this has been fixed.

**Comment by williamstein** [comment]
Yes, this is fixed.  It was due to a scoping issue in coffeescript.
