### ISSUE TITLE
Documentation incorrect for function diff, alias of derivative

### ISSUE THREAD

**Issue by ronindesign** [sagemath/cloud#132]
New to Sage, so I apologize if the format of this ticket is off or if I omit important information.

Discovery: Upon running "diff??" from a .sagews file, I get:
<pre>
--
File: /usr/local/sage/sage-6.2.rc0/local/lib/python2.7/site-packages/sage/calculus/functional.py
   Source:
   def derivative(f, *args, **kwds):
    """
    The derivative of `f`.
    .... etc
--
</pre>
However, upon examining the file "functional.py" I find no definition for derivative function in any form. Perhaps the location of this function was changed, but the documentation has yet to be updated?

Additional info:
- I ran into this issue working on homework for UW course 'MATH 480B'.
- I believe I found the related sage reference documentation: http://www.sagemath.org/doc/reference/calculus/sage/calculus/functional.html

**Comment by kcrisman** [comment]
[This line](http://git.sagemath.org/sage.git/tree/src/sage/calculus/functional.py#n137) actually shows that it is there, and is an alias for `derivative`, whose full code is

    try:
        return f.derivative(*args, **kwds)
    except AttributeError:
        pass
    if not isinstance(f, Expression):
        f = SR(f)
    return f.derivative(*args, **kwds)

Then derivatives are implemented for various kinds of objects - symbolic expressions, polynomials over various rings, or whatever else a derivative might make sense for - individually.

In any case, this is a Sage ticket, not cloud... @haraldschilly @williamstein can close this, I don't see any mechanism for me to mark it as invalid.

**Comment by ronindesign** [comment]
I figured the function and code were present. However the bug is that "diff??" did not seem to bring up any relevant help like other functions do. So maybe a reference needs to be updated?

**Comment by kcrisman** [comment]
I'm not sure I follow.  In your sample code, `diff??` brings up that it's the derivative, and then a host of examples.   What kind of help were you thinking of?  That said, I agree that it could be useful to have even more verbose like [here](http://git.sagemath.org/sage.git/tree/src/sage/symbolic/expression.pyx#n3255) but that would definitely be a Sage ticket.   I'm sorry if I am totally misconstruing your question; an example of a "good" output from `??` might make it clearer.
