### ISSUE TITLE
Problems with MathJax rendering

### ISSUE THREAD

**Issue by gagern** [sagemath/cloud#146]
Rendering MathJax in a Sage worksheet in the cloud doesn't work as expected. Example:

    view(matrix(ZZ,5,5,range(25)))

In the local sage notebook server, this would give me a MathJax rendering of the matrix, but not so on the cloud. There I see no output at all.

**Comment by williamstein** [comment]
We should just set view=show in SMC.

**Comment by williamstein** [comment]
Now view =show.
