### ISSUE TITLE
some sort of very odd workflow issue with ipython (doesn't load new documents without having to clear some cache)

### ISSUE THREAD

**Issue by silky** [sagemath/cloud#151]
i tried the following thing:

 1) create a new project, create a terminal, clone a project with an empty ipython notebook,
 2) open the notebook in SMC (it's empty),
 3) update the notebook to have content, go back to SMC and in the terminal pull down the new changes,
 4) try and get the new ipython document to open

i noticed that it doesn't come up if you click, say, 'reload'. this actually seemed to change the copy of the ipython notebook that SMC had.

so i reverted those changes, and tried opening it. it was STILL blank

then i deleted the backup files SMC keeps:
  
````
~/recipies$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
 
Untracked files:
  (use "git add <file>..." to include in what will be committed)
 
        ..analyse_recipies.ipynb.syncdoc.sage-backup
        .analyse_recipies.ipynb.syncdoc
        .ipynb_checkpoints/
 
nothing added to commit but untracked files present (use "git add" to track)
~/recipies$
~/recipies$ rm -rf .ipynb_checkpoints/
~/recipies$ rm .analyse_recipies.ipynb.syncdoc
~/recipies$ rm ..analyse_recipies.ipynb.syncdoc.sage-backup
~/recipies$ git status
````

only then did it open up correctly.

am i misunderstanding something? there seems to be a clear bug here.

**Comment by haraldschilly** [comment]
in the meantime, syncdoc has changed 2 time to syncdoc3. so closing.
