### ISSUE TITLE
Login doesn't work in safari private browsing mode.

### ISSUE THREAD

**Issue by williamstein** [sagemath/cloud#156]
On Tue, Aug 26, 2014 at 10:30 PM, NDZL <> wrote:
> hi there
> my notes refer to Safari on iOS 7.1.2
> -login fails when safari is in Private browsing. you should advice about that.

Many thanks for reporting that -- I wasn't aware of this bug.   In Chrome private browsing mode login works, but indeed not with Safari.  Moreover, the error is just "unexpected error".

**Comment by haraldschilly** [comment]
safari probably doesn't let you create "virtual" cookies. not much you can do here.
