### ISSUE TITLE
Missing closing bra...

### ISSUE THREAD

**Issue by billpage** [sagemath/cloud#159]
The following example apparently causes a MathJax error that displays

  |Missing close bra|

in a highlighted box. Presumably this should read "Missing closing brace."

The example is cut-and-paste from a Sage worksheet on SMC using Chrome browers.  It apparently includes the generated LaTeX but I am not quite sure how well this cut-and-paste works.  Is the extra stuff related to hash codes, etc.?

<code>
ex2 = -((k-sqrt(k^2+4*l))*cosh(-sqrt(1/2*k+1/2*sqrt(k^2+4*l)))-(k+sqrt(k^2+4*l))*cosh(sqrt(1/2*k-1/2*sqrt(k^2+4*l))))/(2*sqrt(k^2+4*l));ex2
</code>

︡bbe09064-101e-47e1-ae87-47d2167b3824︡{"tex":{"tex":"-\\frac{{\\left(k - \\sqrt{k^{2} + 4 \\, l}\\right)} \\cosh\\left(-\\sqrt{\\frac{1}{2} \\, k + \\frac{1}{2} \\, \\sqrt{k^{2} + 4 \\, l}}\\right) - {\\left(k + \\sqrt{k^{2} + 4 \\, l}\\right)} \\cosh\\left(\\sqrt{\\frac{1}{2} \\, k - \\frac{1}{2} \\, \\sqrt{k^{2} + 4 \\, l}}\\right)}{2 \\, \\sqrt{k^{2} + 4 \\, l}}","display":true}}︡
︠78dc6f28-57c5-47b0-92b5-8f4b8dfeef5c︠

<code>
ex3 = real(ex2).substitute_expression(imag_part(k)==0,imag_part(l)==0,real_part(k)==k,real_part(l)==l).full_simplify();ex3
</code>
︡b35814a0-f036-49fa-943c-69097d1a6b22︡{"tex":{"tex":"\\frac{{\\left| k^{2} + 4 \\, l \\right|} \\cos\\left(\\frac{1}{2} \\, \\sqrt{2} \\sqrt{{\\left| k + \\sqrt{k^{2} + 4 \\, l} \\right|}} \\sin\\left(\\frac{1}{2} \\, \\arctan\\left(\\frac{1}{2} \\, \\sqrt{{\\left| k^{2} + 4 \\, l \\right|}} \\sin\\left(\\frac{1}{2} \\, \\arctan\\left(0, k^{2} + 4 \\, l\\right)\\right), \\frac{1}{2} \\, \\sqrt{{\\left| k^{2} + 4 \\, l \\right|}} \\cos\\left(\\frac{1}{2} \\, \\arctan\\left(0, k^{2} + 4 \\, l\\right)\\right) + \\frac{1}{2} \\, k\\right)\\right)\\right) \\cosh\\left(\\frac{1}{2} \\, \\sqrt{2} \\sqrt{{\\left| k + \\sqrt{k^{2} + 4 \\, l} \\right|}} \\cos\\left(\\frac{1}{2} \\, \\arctan\\left(\\frac{1}{2} \\, \\sqrt{{\\left| k^{2} + 4 \\, l \\right|}} \\sin\\left(\\frac{1}{2} \\, \\arctan\\left(0, k^{2} + 4 \\, l\\right)\\right), \\frac{1}{2} \\, \\sqrt{{\\left| k^{2} + 4 \\, l \\right|}} \\cos\\left(\\frac{1}{2} \\, \\arctan\\left(0, k^{2} + 4 \\, l\\right)\\right) + \\frac{1}{2} \\, k\\right)\\right)\\right) + {\\left| k^{2} + 4 \\, l \\right|} \\cos\\left(\\frac{1}{2} \\, \\sqrt{2} \\sqrt{{\\left| -k + \\sqrt{k^{2} + 4 \\, l} \\right|}} \\sin\\left(\\frac{1}{2} \\, \\arctan\\left(\\frac{1}{2} \\, \\sqrt{{\\left| k^{2} + 4 \\, l \\right|}} \\sin\\left(\\frac{1}{2} \\, \\arctan\\left(0, k^{2} + 4 \\, l\\right)\\right), -\\frac{1}{2} \\, \\sqrt{{\\left| k^{2} + 4 \\, l \\right|}} \\cos\\left(\\frac{1}{2} \\, \\arctan\\left(0, k^{2} + 4 \\, l\\right)\\right) + \\frac{1}{2} \\, k\\right)\\right)\\right) \\cosh\\left(\\frac{1}{2} \\, \\sqrt{2} \\sqrt{{\\left| -k + \\sqrt{k^{2} + 4 \\, l} \\right|}} \\cos\\left(\\frac{1}{2} \\, \\arctan\\left(\\frac{1}{2} \\, \\sqrt{{\\left| k^{2} + 4 \\, l \\right|}} \\sin\\left(\\frac{1}{2} \\, \\arctan\\left(0, k^{2} + 4 \\, l\\right)\\right), -\\frac{1}{2} \\, \\sqrt{{\\left| k^{2} + 4 \\, l \\right|}} \\cos\\left(\\frac{1}{2} \\, \\arctan\\left(0, k^{2} + 4 \\, l\\right)\\right) + \\frac{1}{2} \\, k\\right)\\right)\\right) - {\\left(k \\cos\\left(\\frac{1}{2} \\, \\sqrt{2} \\sqrt{{\\left| k + \\sqrt{k^{2} + 4 \\, l} \\right|}} \\sin\\left(\\frac{1}{2} \\, \\arctan\\left(\\frac{1}{2} \\, \\sqrt{{\\left| k^{2} + 4 \\, l \\right|}} \\sin\\left(\\frac{1}{2} \\, \\arctan\\left(0, k^{2} + 4 \\, l\\right)\\right), \\frac{1}{2} \\, \\sqrt[...]","display":true}}︡
</code>

**Comment by andresjuez** [comment]
Hi billpage, I'm getting the same error... did you finally found any suitable workaround for this issue? Thanks!

**Comment by haraldschilly** [comment]
This smells like a MathJax problem.

**Comment by haraldschilly** [comment]
and the exmple works now
