### ISSUE TITLE
" VTK in line plots " - write_png / Image problem on SageMathCloud

### ISSUE THREAD

**Issue by AndreTimotheo** [sagemath/cloud#161]
I am working very well with Dolfin 1.4 on SageMathCloud. I want to plot in line
the standart dolfin plots on ipyhton notebook of my browser. 

    import matplotlib.pyplot as plt
    
    from IPython.core.display import Image

    from dolfin import *
    
    mesh = UnitSquareMesh(8 , 8) 
    
    mesh_plot = plot(mesh, interactive = False)
    mesh_plot.write_png("mesh")    #  where is it ?
    
    Image(filename = 'mesh.png')

This code works well on ipython qtconsole but on SageMathCloud the 
file mesh.png does not exist. How can I solve this problem? 

Thank you for your time

Andre Machado

**Comment by haraldschilly** [comment]
closing this. maybe it has just been placed into the wrong directory and the MPI problem is solved by using mpich instead of openmpi
