### ISSUE TITLE
Deleting a selection doesn't work

### ISSUE THREAD

**Issue by roed314** [sagemath/cloud#166]
In a sage worksheet, selecting some text and hitting the backspace key results in deleting the last character, leaving the remainder of the text selected.  Hitting another key (such as a letter or Enter) replaces the text with the input, as expected.  This may be an upstream codemirror issue, but it's very annoying.

Firefox 32.0.1 on OS X 10.9.2.

**Comment by haraldschilly** [comment]
Is this still the case? (my guess, related to some browser plugins). I'm in favour of closing it.

**Comment by williamstein** [comment]
I can't replicate this using OS X firefox.

**Comment by roed314** [comment]
I don't know why my setup is so strange.  Closing seems reasonable.
