### ISSUE TITLE
Intermittent failure of IPython notebook sync?

### ISSUE THREAD

**Issue by ceball** [sagemath/cloud#182]
The following screenshot shows that the kernel is idle, and that some cells have finished running (but still show up as ``[*]`` i.e. computing, e.g. the ``%R print(seq(10))`` cell), while others haven't yet run even though I requested them to (e.g. the ``a = %Rget a`` cell):

![screenshot - 151214 - 10 39 09](https://cloud.githubusercontent.com/assets/1929/5434615/7ed6d36c-844b-11e4-8b6e-8d87260acc94.png)

I started from a freshly reset kernel, with all output having been cleared.

I can't always reproduce this state, but when I do get here it's by doing shift+enter on cells one after  another (in this case, starting from the top of the notebook).

I'm sorry that this is a vague bug report. I haven't yet tried to run SageMathCloud on my own machine (though I'd like to at some point). Meanwhile, all I can do is try out suggestions and/or test things.

**Comment by harpone** [comment]
I'm getting that too... do you happen to be quite far from UW (where most of the servers reside?), e.g. in Europe? I seemed to have much fewer problems with sage workseets...

**Comment by haraldschilly** [comment]
since the report of the bug, the storage and IIRC also the syncing of ipynb has changed. closing this.
