### ISSUE TITLE
Palettes

### ISSUE THREAD

**Issue by kcrisman** [sagemath/cloud#186]
Maple and probably others have (optionally) various 'palettes' of things like integrals, symbols, whatnot.  Perhaps some of this is already in SMC; this issue is to record the possibility of more or better-integrated ones in the `.sagews` environment.

**Comment by williamstein** [comment]
Imagine this but on top of a Sage worksheet, and with a few buttons related to math (and also obviously more combining of buttons into menus, which we haven't done yet).  That's on my todo list today.  I might not make it though, since pdf publishing is higher, as is printing stuff for the JMM.   The functionality of the buttons will be context sensitive, e.g., if a (not the) cursor is in a %md cell, then it the result will be different than in a %r cell.

![screen shot 2015-01-08 at 9 55 07 am](https://cloud.githubusercontent.com/assets/1276278/5667442/7fb62236-971c-11e4-8388-5908156f61b7.png)

**Comment by kcrisman** [comment]
Yeah, something along these lines... obviously not as high priority as other stuff, since Sage doesn't currently have it anyway!

And I have to say that any menu-combining you can do with the various icons would be good; currently it's harder to parse than the MS Word interface, which is positively frightening :smiley:

**Comment by kcrisman** [comment]
(By which I mean to say it's exciting that this is so possible, I wasn't expecting it!)

**Comment by williamstein** [comment]
On Thu, Jan 8, 2015 at 10:02 AM, kcrisman <notifications@github.com> wrote:

> (By which I mean to say it's exciting that this is so possible, I wasn't
> expecting it!)
>

It's easy to do and a lot is already combined (e.g., for formatting, font
size, font choice).  However, I wanted to focus on having a first release
and implementing the underlying functionality first.


> --
> Reply to this email directly or view it on GitHub
> <https://github.com/sagemath/cloud/issues/186#issuecomment-69220740>.
>



-- 
William Stein
Professor of Mathematics
University of Washington
http://wstein.org

**Comment by kcrisman** [comment]
By the way, if you can share the end result of the document you are working on with sage-edu and sage-devel, or maybe at an address like http://wiki.sagemath.org/jmms2015, that would be great.

**Comment by williamstein** [comment]
I've made it public here:


https://cloud.sagemath.com/projects/091a4332-78db-432d-8c70-18a0218a7dfd/files/2015/schedule.md

But that will *as of this moment* just show the markdown source.  Rendering
the html is on the insane todo list...

On Thu, Jan 8, 2015 at 10:08 AM, kcrisman <notifications@github.com> wrote:

> By the way, if you can share the end result of the document you are
> working on with sage-edu and sage-devel, or maybe at an address like
> http://wiki.sagemath.org/jmms2015, that would be great.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/sagemath/cloud/issues/186#issuecomment-69221808>.
>



-- 
William Stein
Professor of Mathematics
University of Washington
http://wstein.org

**Comment by haraldschilly** [comment]
I close this issue, because right now there are those toolbars (which do need work) and I am pursuing my idea of that "wizard" dialog.
