### ISSUE TITLE
Collaborative editing not working: edits disappearing

### ISSUE THREAD

**Issue by harpone** [sagemath/cloud#188]
I'm collaborating on a project, and it seems that whenever both are logged in (or if both have been logged in recently), the one who logged in last often has **serious** editing problems. Basically all edits just disappear. 

I am using SMC from Finland and the other guy is on the East Coast USA. Maybe the problem is related to latency differences between collaborators?

**Comment by haraldschilly** [comment]
Could you please post the project ID?

**Comment by harpone** [comment]
Sure, it's d8b23100-cb34-4a16-911e-9bcf3bccf991


Also hostname is compute20dc0, so I guess this is in UW? I got similar
problems when the project was in Europe too (I think).

**Comment by haraldschilly** [comment]
all the code, infrastructure and backend storage did at least change twice since then. I'm closing this.
