### ISSUE TITLE
provide interactive ODE direction field

### ISSUE THREAD

**Issue by rwst** [sagemath/cloud#192]
In desktop Sage users have commands like
```
sage: maxima('plotdf((1-y)*sin(y),[t,y],[t,-4,4],[y,-4,4])')
```
that open an interactive graphics window. But students need this in the cloud, so either the maxima functionality should be adapted to the cloud, or it should be newly implemented.

**Comment by haraldschilly** [comment]
The only possible way is to use the 3d plotting of Sage -- which is kind of a new implementation for this. Making this for maxima is way out of scope for the SMC project :disappointed:

**Comment by rwst** [comment]
In the meantime I found this excellent page which is nowhere advertised (it should be!):
http://wiki.sagemath.org/interact/diffeq
