### ISSUE TITLE
cant install swirl in R-3.4.3 in ubuntu trusty

### ISSUE THREAD

**Issue by saamm** [sagemath/cloud#208]
I cant seem to install swirl in R-3.4.3 in ubuntu trusty I keep getting the error that curl, httr and some other dependencies has non-zero exit status. I dont really know what that means. Also when I try to install libcur14-openssl-dev using terminal, I keep getting the error unable to locate the package.

**Comment by haraldschilly** [comment]
I think you are asking in the wrong place.
