### ISSUE TITLE
high CPU/GPU load 

### ISSUE THREAD

**Issue by P7R8** [sagemath/cloud#25]
it is not yet in this list so...

change in laptop temperature:
- surfing to the login page, 47C to 53C, idle
- after login, constant ~52, idle
- working* with notebook up to +70C

*working=just trying out basic calculus and 2d plotting

Screenshot: after creating 3 tables á 6 cells, idle, 60C

Browser: SWare Iron (=Chrome) Version 27.0.1500.0 (201000)
Setup: Win8, Intel Core2 Duo L7500 @ 1.6GHz, 3GB Ram, GPU Intel 965 Onboard

![60c-idle](https://f.cloud.github.com/assets/5571488/1233913/72118a5c-294b-11e3-9ac2-1ea4a71374e3.jpg)

**Comment by haraldschilly** [comment]
I'm closing this issue, doesn't seem to go anywhere. pymc is currently not installed, because it doesn't build on top of Sage's environment. you could try to use your own python environment via miniconda.
