### ISSUE TITLE
new -> "from web" improvements

### ISSUE THREAD

**Issue by haraldschilly** [sagemath/cloud#51]
There could be a few improvements + additional heuristics for the "from web" button.

* A Url like `https://github.com/sagemath/cloud-examples` could be translated directly to the git repository and not download the HTML, right?
* list a few options what can be loaded from the web to give the user ideas (or add it to a mouse-over bubble box)

:exclamation: insert more ideas in the comments below :exclamation:

**Comment by williamstein** [comment]
closed since we only want clear precise things here (not brainstorms)
