### ISSUE TITLE
Message: Failed to load PDF document

### ISSUE THREAD

**Issue by wbhart** [sagemath/cloud#71]
When editing a latex file in the tex editor, with the PDF view selected, after pressing CTRL-S to save changes to a document, it rebuilds the PDF but often displays "Failed to load PDF document". Sometimes it happens virtually every time, other times it might be one in five or one in ten saves.

Subsequently clicking the PDF button has so far always correctly loaded the PDF when this happens. It feels like a timing issue.

This appears to be a relatively recent issue and did not happen for me with early versions of cloud.sagemath. However, it has persisted over multiple sessions on multiple different days.

This appears to be independent of the actual contents of the pdf, though all my pdfs are at least 5 pages of rendered pdf.

My browser is the latest Google Chrome on Windows 7.

**Comment by haraldschilly** [comment]
I'm closing this. If you see something like that again, please email us the full URL to help@sagemath.com
