### ISSUE TITLE
Add cvxpy and ecos packages

### ISSUE THREAD

**Issue by williamstein** [sagemath/cloud#74]
Whenever you have some free time, I was wondering if you can comment on adding https://github.com/cvxgrp/cvxpy and https://github.com/ifa-ethz/ecos to Sagemath Cloud. I lost half of my time trying to install them offline on Windows or Linux and I'm not done yet. When I started, I expected CVXOPT to be enough but it misses "modeling" ( user-friendliness ).﻿

Requested by Behzad Samadi.

**Comment by haraldschilly** [comment]
This is open since 1 1/2 years. Any progress? (I'm closing it for now)
