### ISSUE TITLE
add 2FA for google authenticator

### ISSUE THREAD

**Issue by haraldschilly** [sagemath/cloud#85]
the google authenticator app allows adding 3rd party websites. the [pyotp library](https://github.com/nathforge/pyotp) contains the HMAC hashing and some helper functions. 

1. instance with user specific secret: `totp = pyotp.TOTP('base32secret3232')`
1. `totp.provisioning_uri("user name @ cloud.sagemath.com")` -> QR code the output -> scan & import it
1. `totp.verify(<user input>)`

maybe it's necessary to also check 30 seconds earlier and later to make up for slightly wrong adjusted times on the phone.

**Comment by haraldschilly** [comment]
if you use a google account, you can have 2FA with a lot of their security extras. just replicating this for native SMC accounts might be more illusion than reality.

**Comment by williamstein** [comment]
I'm not so sure. This may be of value to users who don't want to have a google account.  Some users, e.g., might only want to login to SMC via email/password.   That said, I've never once got a request from 2FA from a user.
