### ISSUE TITLE
encode the filenames before making them into URL links

### ISSUE THREAD

**Issue by williamstein** [sagemath/cloud#99]
From Jason Grout: "One of my students just had a problem when trying to generate a pdf of a sage worksheet that had a # in the name.  The problem is that then, the URL links to the worksheet treat the # as a URL separator.  Instead, you should probably URL encode the filenames before making them into URL links."

**Comment by haraldschilly** [comment]
Not sure how to test this, I think it works (a png file with a "#" did end up as "%23"  in the download link)
